### ISSUE TITLE
[BUG] Client Side XSS 

### ISSUE THREAD

**Issue by austinpickett** [n-for-all/ajaxy-live-search#1]
When typing in the search area such as `<script>alert(1)</script>` you will see a popup appear with 1. the same if you type `<plaintext>` you will see the unformatted code.

This isn't effected if a user is directed to a link: http://example.com/?s=<script>alert(1)</script> you'll get a 403 forbidden, however, these inputs should be sanitized.

**Comment by n-for-all** [comment]
should be fixed with this version, check and let me know
